package m10r.model;
// Generated Jun 27, 2018 9:14:37 PM by Hibernate Tools 4.3.1



/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private int idEmpleado;
     private int idPersona;
     private int idTipoTransaccion;
     private float totalCompra;

    public Compra() {
    }

    public Compra(int idEmpleado, int idPersona, int idTipoTransaccion, float totalCompra) {
       this.idEmpleado = idEmpleado;
       this.idPersona = idPersona;
       this.idTipoTransaccion = idTipoTransaccion;
       this.totalCompra = totalCompra;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public int getIdTipoTransaccion() {
        return this.idTipoTransaccion;
    }
    
    public void setIdTipoTransaccion(int idTipoTransaccion) {
        this.idTipoTransaccion = idTipoTransaccion;
    }
    public float getTotalCompra() {
        return this.totalCompra;
    }
    
    public void setTotalCompra(float totalCompra) {
        this.totalCompra = totalCompra;
    }




}


