package m10r.model;
// Generated Jun 27, 2018 9:14:37 PM by Hibernate Tools 4.3.1



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private Integer idDetalleVenta;
     private int idVenta;
     private int idProducto;
     private float valorVentaProducto;
     private String iva;
     private int unidadesVendidas;

    public DetalleVenta() {
    }

	
    public DetalleVenta(int idVenta, int idProducto, float valorVentaProducto, int unidadesVendidas) {
        this.idVenta = idVenta;
        this.idProducto = idProducto;
        this.valorVentaProducto = valorVentaProducto;
        this.unidadesVendidas = unidadesVendidas;
    }
    public DetalleVenta(int idVenta, int idProducto, float valorVentaProducto, String iva, int unidadesVendidas) {
       this.idVenta = idVenta;
       this.idProducto = idProducto;
       this.valorVentaProducto = valorVentaProducto;
       this.iva = iva;
       this.unidadesVendidas = unidadesVendidas;
    }
   
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public float getValorVentaProducto() {
        return this.valorVentaProducto;
    }
    
    public void setValorVentaProducto(float valorVentaProducto) {
        this.valorVentaProducto = valorVentaProducto;
    }
    public String getIva() {
        return this.iva;
    }
    
    public void setIva(String iva) {
        this.iva = iva;
    }
    public int getUnidadesVendidas() {
        return this.unidadesVendidas;
    }
    
    public void setUnidadesVendidas(int unidadesVendidas) {
        this.unidadesVendidas = unidadesVendidas;
    }




}


