package m10r.model;
// Generated Jun 27, 2018 9:14:37 PM by Hibernate Tools 4.3.1



/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private Integer idTipoDocumento;
     private String descripcionDocumento;

    public TipoDocumento() {
    }

    public TipoDocumento(String descripcionDocumento) {
       this.descripcionDocumento = descripcionDocumento;
    }
   
    public Integer getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Integer idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getDescripcionDocumento() {
        return this.descripcionDocumento;
    }
    
    public void setDescripcionDocumento(String descripcionDocumento) {
        this.descripcionDocumento = descripcionDocumento;
    }




}


