package m10r.model;
// Generated Jun 27, 2018 9:14:37 PM by Hibernate Tools 4.3.1



/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private int idEmpleado;
     private int idPersona;
     private int idTipoTransaccion;
     private float totalVenta;
     private float totalDescuentoVenta;

    public Venta() {
    }

    public Venta(int idEmpleado, int idPersona, int idTipoTransaccion, float totalVenta, float totalDescuentoVenta) {
       this.idEmpleado = idEmpleado;
       this.idPersona = idPersona;
       this.idTipoTransaccion = idTipoTransaccion;
       this.totalVenta = totalVenta;
       this.totalDescuentoVenta = totalDescuentoVenta;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public int getIdTipoTransaccion() {
        return this.idTipoTransaccion;
    }
    
    public void setIdTipoTransaccion(int idTipoTransaccion) {
        this.idTipoTransaccion = idTipoTransaccion;
    }
    public float getTotalVenta() {
        return this.totalVenta;
    }
    
    public void setTotalVenta(float totalVenta) {
        this.totalVenta = totalVenta;
    }
    public float getTotalDescuentoVenta() {
        return this.totalDescuentoVenta;
    }
    
    public void setTotalDescuentoVenta(float totalDescuentoVenta) {
        this.totalDescuentoVenta = totalDescuentoVenta;
    }




}


